### ISSUE TITLE
[DOCS] Write comments

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/let-it-be#2]
Try to understand what the code does and write a comment on how it works in HTML, CSS, JS files.

**Comment by RohitRajvaidya5** [comment]
Hey, is this issue resolved? can I work on this?

**Comment by KendallDoesCoding** [comment]
> Hey, is this issue resolved? can I work on this?

Sure!

**Comment by RohitRajvaidya5** [comment]
Done ! ✅

**Comment by KendallDoesCoding** [comment]
> Done ! ✅

Please see my comments in your PR.

**Comment by RohitRajvaidya5** [comment]
Sure I will try same for CSS 👍🏻
